import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import {useEffect, useState, VFC} from 'react'
import {useTeams} from "@/hooks/use-teams";
import {useProject, useProjects} from "@/hooks/use-projects";

const Home: VFC = () => {
  const [selectedTeam, setSelectedTeam] = useState<string>()
  const [selectedProject, setSelectedProject] = useState<string>()
  const teams = useTeams()
  useEffect(() => {
    setSelectedTeam(teams?.teams?.[0]?.id)
  }, [teams])
  const projects = useProjects(selectedTeam)

  const project = useProject(selectedProject ?? '', selectedTeam)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {teams && (
          <select onChange={(e) => setSelectedTeam(e.target.value)}>
            {teams.teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}
          </select>
        )}
        <select onChange={(e) => setSelectedProject(e.target.value)}>
          {projects?.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}
        </select>

        <p>{project?.targets?.production?.name}</p>
        <p>{project?.targets?.production?.readyState}</p>
        <p>{project?.targets?.production?.createdAt && new Date(project?.targets?.production?.createdAt).toLocaleString()}</p>
        {console.log(project)}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
